'use client';

import { FormEvent, useEffect, useMemo, useState } from 'react';
import { Brain, CheckCircle2, Plus, RefreshCw, Save } from 'lucide-react';
import { AdminShell } from '@/components/AdminShell';
import { api } from '@/lib/api';

type Plant = { id:number; name:string; code?:string|null; description?:string|null; isActive:boolean; defaultRecipeId?:number|null; defaultLeafStockCardId?:number|null; defaultTrunkStockCardId?:number|null; defaultPotStockCardId?:number|null; defaultRecipe?:{name:string}|null; defaultLeafStockCard?:Stock|null; defaultTrunkStockCard?:Stock|null; defaultPotStockCard?:Stock|null };
type Stock = { id:number; name:string; sku?:string|null; category?:string|null; unit?:string|null };
type Alias = { id:number; alias:string; normalizedAlias:string; entityType:string; priority:number; isActive:boolean; plantType?:Plant|null; potProfile?:Pot|null };
type Pot = { id:number; name:string; materialType?:string|null; color?:string|null; width?:string|null; depth?:string|null; height?:string|null; stockCardId?:number|null; stockCard?:Stock|null; isActive:boolean };
type Recipe = { id:number; name:string; plantTypeId?:number|null; minHeightCm?:number|null; maxHeightCm?:number|null; isActive:boolean; plantType?:Plant|null; items:unknown[] };
type Rule = { id:number; name:string; ruleKind:string; plantTypeId?:number|null; heightCm?:number|null; stockCardId?:number|null; quantity?:string|null; unit?:string|null; amountTl?:string|null; priority:number; isActive:boolean; plantType?:Plant|null; stockCard?:Stock|null };
type Log = { id:number; inputText:string; normalizedInput:string; detectedHeightCm?:number|null; confidenceScore:string; decisionStatus:string; matchedRecipeId?:number|null; createdAt:string; detectedPlantType?:Plant|null; detectedPotProfile?:Pot|null; resultJson?:{potProfile?:{name?:string}|null;recipeProfile?:{name?:string}|null}|null; feedbacks:Array<{id:number;fieldName:string;createdAt:string}> };

const tabs = ['Bitki Aileleri','Eş Anlamlılar','Reçeteler','Boy Kuralları','Saksılar','Yaprak Kuralları','Gövde Kuralları','Taş Kuralları','Silikon Kuralları','İşçilik Kuralları','Analiz Logları'] as const;
type Tab = typeof tabs[number];
const kindByTab:Partial<Record<Tab,string>> = {'Boy Kuralları':'HEIGHT','Yaprak Kuralları':'LEAF','Gövde Kuralları':'TRUNK','Taş Kuralları':'STONE','Silikon Kuralları':'SILICONE','İşçilik Kuralları':'LABOR'};

export default function KnowledgeCenterPage(){
  const [tab,setTab]=useState<Tab>('Bitki Aileleri');
  const [plants,setPlants]=useState<Plant[]>([]); const [stocks,setStocks]=useState<Stock[]>([]); const [aliases,setAliases]=useState<Alias[]>([]);
  const [pots,setPots]=useState<Pot[]>([]); const [recipes,setRecipes]=useState<Recipe[]>([]); const [rules,setRules]=useState<Rule[]>([]); const [logs,setLogs]=useState<Log[]>([]);
  const [message,setMessage]=useState(''); const [loading,setLoading]=useState(true);
  async function load(){setLoading(true);setMessage('');try{const [a,b,c,d,e,f,g]=await Promise.all([
    api<Plant[]>('/knowledge-base/plant-types'),api<Stock[]>('/knowledge-base/stock-card-options'),api<Alias[]>('/knowledge-base/aliases'),api<Pot[]>('/knowledge-base/pot-profiles'),api<Recipe[]>('/knowledge-base/recipe-profiles'),api<Rule[]>('/knowledge-base/rules'),api<Log[]>('/knowledge-base/analysis-logs?take=150')]);
    setPlants(a);setStocks(b);setAliases(c);setPots(d);setRecipes(e);setRules(f);setLogs(g);}catch(error){setMessage(error instanceof Error?error.message:'Bilgi Merkezi yüklenemedi.');}finally{setLoading(false)}}
  useEffect(()=>{load()},[]);
  const kind=kindByTab[tab];
  return <AdminShell title="Bilgi Merkezi"><div className="space-y-4">
    <section className="panel p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-3"><Brain className="text-brand"/><div><h2 className="font-bold">Ürün Bilgisi ve Kural Yönetimi</h2><p className="text-sm text-slate-500">Analiz kuralları development veritabanından yönetilir.</p></div></div><button className="btn btn-secondary" onClick={load}><RefreshCw size={16}/>Yenile</button></div>
    {message&&<div className="mt-3 rounded-md bg-amber-50 p-3 text-sm font-semibold text-amber-800">{message}</div>}
    <div className="mt-4 flex gap-2 overflow-x-auto pb-1">{tabs.map(x=><button key={x} onClick={()=>setTab(x)} className={`whitespace-nowrap rounded-md px-3 py-2 text-sm font-semibold ${tab===x?'bg-brand text-white':'bg-slate-100 text-slate-700'}`}>{x}</button>)}</div></section>
    {loading?<section className="panel p-8 text-center text-sm text-slate-500">Yükleniyor...</section>:<>
      {tab==='Bitki Aileleri'&&<Plants plants={plants} stocks={stocks} recipes={recipes} reload={load}/>} 
      {tab==='Eş Anlamlılar'&&<Aliases aliases={aliases} plants={plants} pots={pots} reload={load}/>} 
      {tab==='Reçeteler'&&<Recipes recipes={recipes} plants={plants} reload={load}/>} 
      {tab==='Saksılar'&&<Pots pots={pots} stocks={stocks} reload={load}/>} 
      {kind&&<Rules title={tab} kind={kind} rules={rules.filter(x=>x.ruleKind===kind)} plants={plants} stocks={stocks} reload={load}/>} 
      {tab==='Analiz Logları'&&<Logs logs={logs} reload={load}/>} 
    </>}</div></AdminShell>
}

function Plants({plants,stocks,recipes,reload}:{plants:Plant[];stocks:Stock[];recipes:Recipe[];reload:()=>Promise<void>}){
 const [f,setF]=useState({name:'',code:'',description:'',defaultRecipeId:'',defaultLeafStockCardId:'',defaultTrunkStockCardId:'',defaultPotStockCardId:''});
 async function submit(e:FormEvent){e.preventDefault();await api('/knowledge-base/plant-types',{method:'POST',json:{...f,defaultRecipeId:num(f.defaultRecipeId),defaultLeafStockCardId:num(f.defaultLeafStockCardId),defaultTrunkStockCardId:num(f.defaultTrunkStockCardId),defaultPotStockCardId:num(f.defaultPotStockCardId)}});setF({name:'',code:'',description:'',defaultRecipeId:'',defaultLeafStockCardId:'',defaultTrunkStockCardId:'',defaultPotStockCardId:''});await reload()}
 return <Section title="Bitki Aileleri" count={plants.length}><form onSubmit={submit} className="grid gap-3 md:grid-cols-2 xl:grid-cols-4"><Input label="Aile Adı" value={f.name} set={v=>setF({...f,name:v})}/><Input label="Kod" value={f.code} set={v=>setF({...f,code:v})}/><Select label="Varsayılan Reçete" value={f.defaultRecipeId} set={v=>setF({...f,defaultRecipeId:v})} options={recipes.map(x=>[x.id,x.name])}/><Select label="Varsayılan Yaprak" value={f.defaultLeafStockCardId} set={v=>setF({...f,defaultLeafStockCardId:v})} options={stocks.map(x=>[x.id,x.name])}/><Select label="Varsayılan Gövde" value={f.defaultTrunkStockCardId} set={v=>setF({...f,defaultTrunkStockCardId:v})} options={stocks.map(x=>[x.id,x.name])}/><Select label="Varsayılan Saksı" value={f.defaultPotStockCardId} set={v=>setF({...f,defaultPotStockCardId:v})} options={stocks.map(x=>[x.id,x.name])}/><Input label="Açıklama" value={f.description} set={v=>setF({...f,description:v})}/><SaveButton/></form><Table heads={['Aile','Kod','Reçete','Yaprak','Gövde','Saksı','Durum']} rows={plants.map(x=>[x.name,x.code||'-',x.defaultRecipe?.name||'-',x.defaultLeafStockCard?.name||'-',x.defaultTrunkStockCard?.name||'-',x.defaultPotStockCard?.name||'-',<Toggle key={x.id} active={x.isActive} onClick={async()=>{await api(`/knowledge-base/plant-types/${x.id}`,{method:'PATCH',json:{isActive:!x.isActive}});await reload()}}/>])}/></Section>
}

function Aliases({aliases,plants,pots,reload}:{aliases:Alias[];plants:Plant[];pots:Pot[];reload:()=>Promise<void>}){const [f,setF]=useState({alias:'',entityType:'PLANT_TYPE',target:''});async function submit(e:FormEvent){e.preventDefault();await api('/knowledge-base/aliases',{method:'POST',json:{alias:f.alias,entityType:f.entityType,plantTypeId:f.entityType==='PLANT_TYPE'?num(f.target):null,potProfileId:f.entityType==='POT_PROFILE'?num(f.target):null}});setF({...f,alias:'',target:''});await reload()}const targets=f.entityType==='PLANT_TYPE'?plants.map(x=>[x.id,x.name] as [number,string]):pots.map(x=>[x.id,x.name] as [number,string]);return <Section title="Eş Anlamlılar" count={aliases.length}><form onSubmit={submit} className="grid gap-3 md:grid-cols-4"><Input label="Eş Anlamlı" value={f.alias} set={v=>setF({...f,alias:v})}/><Select label="Tür" value={f.entityType} set={v=>setF({...f,entityType:v,target:''})} options={[["PLANT_TYPE","Bitki Ailesi"],["POT_PROFILE","Saksı"]]}/><Select label="Bağlanacak Kayıt" value={f.target} set={v=>setF({...f,target:v})} options={targets}/><SaveButton/></form><Table heads={['Yazım','Normalize','Hedef','Durum']} rows={aliases.map(x=>[x.alias,x.normalizedAlias,x.plantType?.name||x.potProfile?.name||'-',x.isActive?'Aktif':'Pasif'])}/></Section>}

function Recipes({recipes,plants,reload}:{recipes:Recipe[];plants:Plant[];reload:()=>Promise<void>}){const [f,setF]=useState({name:'',plantTypeId:'',minHeightCm:'',maxHeightCm:''});async function submit(e:FormEvent){e.preventDefault();await api('/knowledge-base/recipe-profiles',{method:'POST',json:{name:f.name,plantTypeId:num(f.plantTypeId),minHeightCm:num(f.minHeightCm),maxHeightCm:num(f.maxHeightCm),items:[]}});setF({name:'',plantTypeId:'',minHeightCm:'',maxHeightCm:''});await reload()}return <Section title="Reçeteler" count={recipes.length}><form onSubmit={submit} className="grid gap-3 md:grid-cols-5"><Input label="Reçete Adı" value={f.name} set={v=>setF({...f,name:v})}/><Select label="Aile" value={f.plantTypeId} set={v=>setF({...f,plantTypeId:v})} options={plants.map(x=>[x.id,x.name])}/><Input label="En Az Boy" type="number" value={f.minHeightCm} set={v=>setF({...f,minHeightCm:v})}/><Input label="En Fazla Boy" type="number" value={f.maxHeightCm} set={v=>setF({...f,maxHeightCm:v})}/><SaveButton/></form><Table heads={['Reçete','Aile','Boy Aralığı','Kalem','Durum']} rows={recipes.map(x=>[x.name,x.plantType?.name||'-',`${x.minHeightCm??'-'} - ${x.maxHeightCm??'-'} cm`,x.items.length,x.isActive?'Aktif':'Pasif'])}/></Section>}

function Pots({pots,stocks,reload}:{pots:Pot[];stocks:Stock[];reload:()=>Promise<void>}){const [f,setF]=useState({name:'',materialType:'',color:'',width:'',depth:'',height:'',stockCardId:''});async function submit(e:FormEvent){e.preventDefault();await api('/knowledge-base/pot-profiles',{method:'POST',json:{...f,stockCardId:num(f.stockCardId)}});setF({name:'',materialType:'',color:'',width:'',depth:'',height:'',stockCardId:''});await reload()}return <Section title="Saksılar" count={pots.length}><form onSubmit={submit} className="grid gap-3 md:grid-cols-4 xl:grid-cols-8"><Input label="Saksı Adı" value={f.name} set={v=>setF({...f,name:v})}/><Input label="Malzeme" value={f.materialType} set={v=>setF({...f,materialType:v})}/><Input label="Renk" value={f.color} set={v=>setF({...f,color:v})}/><Input label="En" value={f.width} set={v=>setF({...f,width:v})}/><Input label="Boy" value={f.depth} set={v=>setF({...f,depth:v})}/><Input label="Yükseklik" value={f.height} set={v=>setF({...f,height:v})}/><Select label="Stok Kartı" value={f.stockCardId} set={v=>setF({...f,stockCardId:v})} options={stocks.map(x=>[x.id,x.name])}/><SaveButton/></form><Table heads={['Saksı','Malzeme','Renk','Ölçü','Stok Kartı','Durum']} rows={pots.map(x=>[x.name,x.materialType||'-',x.color||'-',[x.width,x.depth,x.height].filter(Boolean).join(' x ')||'-',x.stockCard?.name||'-',x.isActive?'Aktif':'Pasif'])}/></Section>}

function Rules({title,kind,rules,plants,stocks,reload}:{title:string;kind:string;rules:Rule[];plants:Plant[];stocks:Stock[];reload:()=>Promise<void>}){const [f,setF]=useState({name:'',plantTypeId:'',heightCm:'',stockCardId:'',quantity:'',unit:kind==='STONE'?'KG':kind==='LABOR'?'Dakika':'Adet',amountTl:'',priority:'100'});const showStock=!['HEIGHT','LABOR','SILICONE'].includes(kind);async function submit(e:FormEvent){e.preventDefault();await api('/knowledge-base/rules',{method:'POST',json:{...f,ruleKind:kind,plantTypeId:num(f.plantTypeId),heightCm:num(f.heightCm),stockCardId:showStock?num(f.stockCardId):null,quantity:num(f.quantity),amountTl:num(f.amountTl),priority:num(f.priority)}});setF({...f,name:'',heightCm:'',stockCardId:'',quantity:'',amountTl:''});await reload()}return <Section title={title} count={rules.length}><form onSubmit={submit} className="grid gap-3 md:grid-cols-4 xl:grid-cols-8"><Input label="Kural Adı" value={f.name} set={v=>setF({...f,name:v})}/><Select label="Aile" value={f.plantTypeId} set={v=>setF({...f,plantTypeId:v})} options={plants.map(x=>[x.id,x.name])}/><Input label="Boy (cm)" type="number" value={f.heightCm} set={v=>setF({...f,heightCm:v})}/>{showStock&&<Select label="Stok Kartı" value={f.stockCardId} set={v=>setF({...f,stockCardId:v})} options={stocks.map(x=>[x.id,x.name])}/>}<Input label={kind==='LABOR'?'Süre':'Miktar'} type="number" value={f.quantity} set={v=>setF({...f,quantity:v})}/><Input label="Birim" value={f.unit} set={v=>setF({...f,unit:v})}/>{['LABOR','SILICONE'].includes(kind)&&<Input label="Tutar (TL)" type="number" value={f.amountTl} set={v=>setF({...f,amountTl:v})}/>}<SaveButton/></form><Table heads={['Kural','Aile','Boy','Stok Kartı','Miktar','TL','Durum']} rows={rules.map(x=>[x.name,x.plantType?.name||'Tümü',x.heightCm?`${x.heightCm} cm`:'Tümü',x.stockCard?.name||'-',`${x.quantity??'-'} ${x.unit??''}`,x.amountTl?`${x.amountTl} TL`:'-',<Toggle key={x.id} active={x.isActive} onClick={async()=>{await api(`/knowledge-base/rules/${x.id}`,{method:'PATCH',json:{isActive:!x.isActive}});await reload()}}/>])}/></Section>}

function Logs({logs,reload}:{logs:Log[];reload:()=>Promise<void>}){const [feedback,setFeedback]=useState<Record<number,string>>({});async function send(log:Log){const corrected=feedback[log.id]?.trim();if(!corrected)return;await api(`/knowledge-base/analysis-logs/${log.id}/feedback`,{method:'POST',json:{fieldName:'manualCorrection',detectedValue:{plant:log.detectedPlantType?.name,pot:log.detectedPotProfile?.name||log.resultJson?.potProfile?.name},correctedValue:{value:corrected},note:'Bilgi Merkezi kullanıcı düzeltmesi'}});setFeedback({...feedback,[log.id]:''});await reload()}return <Section title="Analiz Logları" count={logs.length}><div className="space-y-3">{logs.map(x=>{const pct=Math.round(Number(x.confidenceScore)*100);const pot=x.detectedPotProfile?.name||x.resultJson?.potProfile?.name||'Saksı yok';const recipe=x.resultJson?.recipeProfile?.name;return <article key={x.id} className="rounded-md border border-line p-4"><div className="grid gap-3 lg:grid-cols-[1.3fr_1fr_100px_170px]"><div><div className="font-semibold">{x.inputText}</div><div className="text-xs text-slate-500">{x.normalizedInput}</div></div><div className="text-sm">{x.detectedPlantType?.name||'Aile bulunamadı'} · {x.detectedHeightCm?`${x.detectedHeightCm} cm`:'Boy yok'} · {pot}{recipe?` · ${recipe}`:''}</div><div className={`font-bold ${pct>=90?'text-emerald-700':pct>=70?'text-amber-700':'text-red-700'}`}>%{pct}</div><Status value={x.decisionStatus}/></div><div className="mt-3 flex gap-2"><input className="field" placeholder="Yanlış eşleşmeyi düzelt" value={feedback[x.id]||''} onChange={e=>setFeedback({...feedback,[x.id]:e.target.value})}/><button className="btn btn-secondary" onClick={()=>send(x)}><CheckCircle2 size={16}/>Düzeltmeyi Kaydet</button></div></article>})}</div></Section>}

function Section({title,count,children}:{title:string;count?:number;children:React.ReactNode}){return <section className="panel p-5"><div className="mb-4 flex items-center justify-between"><h2 className="text-lg font-bold">{title}</h2>{count!==undefined&&<span className="text-sm text-slate-500">{count} kayıt</span>}</div>{children}</section>}
function Input({label,value,set,type='text'}:{label:string;value:string;set:(v:string)=>void;type?:string}){return <label className="text-xs font-semibold text-slate-600">{label}<input className="field mt-1" type={type} value={value} onChange={e=>set(e.target.value)} required={label.includes('Adı')}/></label>}
function Select({label,value,set,options}:{label:string;value:string;set:(v:string)=>void;options:Array<[number|string,string]>}){return <label className="text-xs font-semibold text-slate-600">{label}<select className="field mt-1" value={value} onChange={e=>set(e.target.value)}><option value="">Seç</option>{options.map(([v,n])=><option key={v} value={v}>{n}</option>)}</select></label>}
function SaveButton(){return <button className="btn btn-primary justify-center self-end"><Plus size={16}/>Kaydet</button>}
function Toggle({active,onClick}:{active:boolean;onClick:()=>void}){return <button className={`rounded px-2 py-1 text-xs font-bold ${active?'bg-emerald-50 text-emerald-700':'bg-slate-100 text-slate-600'}`} onClick={onClick}>{active?'Aktif':'Pasif'}</button>}
function Table({heads,rows}:{heads:string[];rows:React.ReactNode[][]}){return <div className="mt-5 overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr>{heads.map(x=><th className="px-3 py-3" key={x}>{x}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr className="border-t border-line" key={i}>{r.map((x,j)=><td className="px-3 py-3" key={j}>{x}</td>)}</tr>)}</tbody></table></div>}
function Status({value}:{value:string}){const labels:Record<string,string>={AUTO_APPLY:'Otomatik Uygula',SUGGEST:'Kullanıcıya Öner',REVIEW_REQUIRED:'İnceleme Gerekli',CORRECTED:'Kullanıcı Düzeltti'};return <span className="rounded bg-slate-100 px-2 py-1 text-center text-xs font-bold">{labels[value]||value}</span>}
function num(v:string){return v===''?null:Number(v)}
