ALTER TABLE "categories"
  ADD COLUMN IF NOT EXISTS "platforms"   TEXT[]   NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS "has_banner"  BOOLEAN  NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "sort_order"  INTEGER  NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "description" TEXT;
